spring:
  application:
    name=spring-web-basic

# 로컬 호스트 개발용
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
    port: 8080

logging:
  level:
    com.codeit.springwebbasic.common.log.LogExample: debug
    org.springframework.web: warn

  file:
    name: C:/Users/user/Workspace/codeit-sprint-bootcamp/logs/app.log

springdoc:
  swagger-ui:
    path: /api-docs-ui.html # UI page 경로
    tags-sorter: alpha # 태그 정렬 방식 (알파벳순)
    operations-sorter: method #메서드 정렬 방식
    display-request-duration: true # 요청에 소요된 시간 표시
    doc-expansion: list # 문서 펼침 상태 (none, list, full)

api-docs:
  path: /my-api # Swagger가 우리 API의 정보를 얻어오기 위해서 요청하는 url

---
# Docker 환경용 프로필 (스프링 초기화시 프로필 active가 docker라면 아래 설정을 우선시하겠다.)
# url: jdbc:postgresql://host.docker.internal:5433/postgres # docker network를 안쓰는 경우
# url: jdbc:postgresql://my-postgres:5432/postgres # docker network를 쓰는 경우, 포트포워딩을 하지 않음

spring:
  config:
    activate:
      on-profile: docker

  # 환경변수로 외부에서 주입 받음.
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}